apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: ingress-basic
  name: ariftest-westus-cloudapp-azure-com-staging
spec:
  secretName: ariftest-westus-cloudapp-azure-com-staging
  dnsNames:
  - ariftest.westus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ariftest.westus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  
